name: water
description: simple demo invoking water
tags:
initialize:
  plugins:
    watt-time:
      method: WattTimeGridEmissions
      path: '@grnsft/if-unofficial-plugins'
    "sci-e":
      method: SciE
      path: "@grnsft/if-plugins"
    sci-o:
      verbose: false
      method: SciO
      path: "@grnsft/if-plugins"
    "sci-m": # a model that calculates m from te, tir, el, rr and rtor
      method: SciM
      verbose: false
      path: "@grnsft/if-plugins"
    sci:
      kind: plugin
      method: Sci
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - watt-time
        - sci-e
        - sci-o
        - sci-m 
        - sci 
      defaults:
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
      config:
        sci-e:
        sci:
          functional-unit-time: 1 sec
          functional-unit: requests # factor to convert per time to per f.unit
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 36000
          cloud/region-wt-id: CAISO_NORTH
          cpu/energy: 0.001
          memory/energy: 0.0005
          network/energy: 0.0005
          requests: 100