name: watt-time
description: simple demo invoking watt-time
tags:
initialize:
  plugins:
    watt-time:
      method: WattTimeGridEmissions
      path: '@grnsft/if-unofficial-plugins'
tree:
  children:
    child:
      pipeline:
        - watt-time
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 36000
          cloud/region-wt-id: CAISO_NORTH